[package]
name = "oxyromon"
version = "0.1.0"
authors = ["Maxime Gauduin <alucryd@archlinux.org>"]
license = "GPL-3.0+"
description = "Rusty ROM Manager"
readme = "README.md"
repository = "https://github.com/alucryd/oxyromon"
keywords = ["cli", "rom"]

[dependencies]
clap = "2.33.1"
crc = "1.8.1"
diesel = { version = "1.4.5", features = ["postgres", "uuidv07"] }
dotenv = "0.15.0"
quick-xml = { version = "0.18.1", features = ["serialize"] }
rayon = "1.3.1"
regex = "1.3.9"
serde = { version = "1.0.111", features = ["derive"] }
simple-error = "0.2.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }

[[bin]]
name = "oxyromon"
path = "src/main.rs"
