[package]
authors = ["Maxime Gauduin <alucryd@archlinux.org>"]
categories = ["command-line-utilities", "games"]
description = "Rusty ROM OrgaNizer"
edition = "2021"
exclude = [".github/", "dist/", "tests/"]
homepage = "https://github.com/alucryd/oxyromon"
keywords = ["cli", "rom", "tool"]
license = "GPL-3.0+"
name = "oxyromon"
readme = "README.md"
repository = "https://github.com/alucryd/oxyromon"
version = "0.15.0"

[features]
default = ["use-rustls", "enable-asm", "chd", "cso", "ird", "rvz"]
use-native-tls = ["sqlx/runtime-async-std-native-tls", "surf/h1-client"]
use-rustls = ["sqlx/runtime-async-std-rustls", "surf/h1-client-rustls"]
enable-asm = ["md-5/asm", "sha1/asm"]
chd = []
cso = []
ird = ["flate2", "strsim"]
rvz = []
benchmark = []
server = [
    "async-ctrlc",
    "async-graphql",
    "async-graphql-tide",
    "async-trait",
    "http-types",
    "tide",
]

[dependencies]
async-ctrlc = { version = "1.2.0", optional = true }
async-graphql = { version = "5.0.8", features = [
    "dataloader",
], default-features = false, optional = true }
async-graphql-tide = { version = "5.0.8", optional = true }
async-std = { version = "1.12.0", features = ["attributes"] }
async-trait = { version = "0.1.68", optional = true }
cfg-if = "1.0.0"
clap = "4.2.7"
crc32fast = "1.3.2"
dialoguer = "0.10.4"
digest = { version = "0.10.6", features = ["std"] }
dirs = "5.0.1"
dotenv = "0.15.0"
flate2 = { version = "1.0.26", optional = true }
futures = "0.3.28"
http-types = { version = "2.12.0", optional = true }
indicatif = { version = "0.17.3", features = ["rayon"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
md-5 = "0.10.5"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.17.1"
phf = { version = "0.11.1", features = ["macros"] }
quick-xml = { version = "0.28.2", features = ["serialize"] }
rayon = "1.7.0"
regex = "1.8.1"
rust-embed = { version = "6.6.1", features = [
    "compression",
    "interpolate-folder-path",
] }
serde = { version = "1.0.163", features = ["derive"] }
sha1 = "0.10.5"
shiratsu-naming = "0.1.7"
simple-error = "0.3.0"
sqlx = { version = "0.6.3", features = ["migrate", "offline", "sqlite"] }
strsim = { version = "0.10.0", optional = true }
strum = { version = "0.24.1", features = ["derive"] }
surf = { version = "2.3.2", default-features = false }
tempfile = "3.5.0"
tide = { version = "0.16.0", features = [
    "h1-server",
], default-features = false, optional = true }
vec-drain-where = "1.0.1"
walkdir = "2.3.3"
zip = { version = "0.6.6", features = ["deflate"], default-features = false }

[dev-dependencies]
serde_json = "1.0.96"
wiremock = "0.5.18"

[[bin]]
name = "oxyromon"
path = "src/main.rs"
