[package]
name = "oxyromon"
version = "0.5.0"
authors = ["Maxime Gauduin <alucryd@archlinux.org>"]
license = "GPL-3.0+"
description = "Rusty ROM OrgaNizer"
edition = "2018"
homepage = "https://github.com/alucryd/oxyromon"
readme = "README.md"
repository = "https://github.com/alucryd/oxyromon"
keywords = ["cli", "rom", "tool"]
categories = ["command-line-utilities", "games"]
exclude = ["test/"]

[dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
cfg-if = "1.0.0"
clap = "2.33.3"
crc32fast = "1.2.1"
digest = { version = "0.9.0", features = ["std"] }
dirs = "3.0.1"
dotenv = "0.15.0"
indicatif = "0.15.0"
once_cell = "1.5.2"
quick-xml = { version = "0.20.0", features = ["serialize"] }
rayon = "1.5.0"
refinery = { version = "0.5.0", features = ["rusqlite"] }
regex = "1.4.3"
serde = { version = "1.0.119", features = ["derive"] }
simple-error = "0.2.3"
sqlx = { version = "0.4.2", features = ["offline", "runtime-async-std-native-tls", "sqlite"] }
tempfile = "3.2.0"

[target.'cfg(windows)'.dependencies.libsqlite3-sys]
version = "0.20.1"
features = ["bundled"]

[[bin]]
name = "oxyromon"
path = "src/main.rs"
