[package]
authors = ["Maxime Gauduin <alucryd@archlinux.org>"]
categories = ["command-line-utilities", "games"]
description = "Rusty ROM OrgaNizer"
edition = "2021"
exclude = [".github/", "dist/", "tests/"]
homepage = "https://github.com/alucryd/oxyromon"
keywords = ["cli", "rom", "tool"]
license = "GPL-3.0+"
name = "oxyromon"
readme = "README.md"
repository = "https://github.com/alucryd/oxyromon"
version = "0.19.0-beta"
rust-version = "1.75.0"

[features]
default = ["use-rustls", "enable-asm"]
use-native-tls = ["reqwest/default-tls"]
use-rustls = ["reqwest/rustls-tls"]
enable-asm = ["md-5/asm", "sha1/asm"]
server = ["async-graphql", "async-graphql-axum", "axum", "http-types"]

[dependencies]
async-graphql = { version = "7.0.3", features = [
    "dataloader",
], default-features = false, optional = true }
async-graphql-axum = { version = "7.0.3", optional = true }
axum = { version = "0.7.5", default-features = false, features = [
    "http2",
    "tokio",
    "ws",
], optional = true }
cfg-if = "1.0.0"
clap = "4.5.4"
crc32fast = "1.4.0"
dialoguer = "0.11.0"
digest = { version = "0.10.7", features = ["std"] }
dirs = "5.0.1"
dotenvy = "0.15.7"
env_logger = "0.11.3"
flate2 = "1.0.28"
futures = "0.3.30"
http-types = { version = "2.12.0", optional = true }
indexmap = { version = "2.2.6", default-features = false, features = ["std", "rayon"] }
indicatif = { version = "0.17.8", features = ["rayon"] }
itertools = "0.12.1"
lazy_static = "1.4.0"
log = "0.4.21"
md-5 = "0.10.6"
num-derive = "0.4.2"
num-traits = "0.2.18"
once_cell = "1.19.0"
phf = { version = "0.11.2", features = ["macros"] }
quick-xml = { version = "0.31.0", features = ["serialize"] }
rayon = "1.10.0"
regex = "1.10.4"
reqwest = { version = "0.12.3", default-features = false }
rust-embed = { version = "8.3.0", features = ["compression"] }
serde = { version = "1.0.197", features = ["derive"] }
sha1 = "0.10.6"
shiratsu-naming = "0.1.7"
simple-error = "0.3.0"
sqlx = { version = "0.7.4", default-features = false, features = [
    "macros",
    "migrate",
    "runtime-tokio",
    "sqlite",
] }
strsim = "0.11.1"
strum = { version = "0.26.2", features = ["derive"] }
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = [
    "fs",
    "io-std",
    "io-util",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
] }
vec-drain-where = "1.0.1"
walkdir = "2.5.0"
zip = { version = "0.6.6", features = ["deflate"], default-features = false }

[dev-dependencies]
serde_json = "1.0.115"
wiremock = "0.6.0"

[[bin]]
name = "oxyromon"
path = "src/main.rs"

[profile.dev]
debug = 2

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
