name: CD

on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{matrix.target}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            aarch64-unknown-linux-gnu,
            aarch64-unknown-linux-musl,
            armv7-unknown-linux-gnueabihf,
            armv7-unknown-linux-musleabihf,
            x86_64-apple-darwin,
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-gnu,
            x86_64-unknown-linux-musl,
          ]
    steps:
      - uses: actions/checkout@master
      - name: Build and release
        uses: Douile/rust-build.action@v0.1.7
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUSTTARGET: ${{matrix.target}}
          EXTRA_FILES: "CHANGELOG.md README.md LICENSE"
