name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, llvm-tools
          override: true
      - name: Install dependencies
        run: sudo apt-get install liblz4-1 libuv1 libzopfli1 mame-tools yarn
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          args: --features benchmark,server
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features benchmark,server
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features benchmark,server
        env:
          CARGO_INCREMENTAL: '0'
          LLVM_PROFILE_FILE: 'cargo-test-%p-%m.profraw'
          RUSTFLAGS: '-Cinstrument-coverage'
      - uses: actions-rs/grcov@v0.1
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
